#+TITLE: A simple XDCC downloader written in python3.

* Description
  *xdcc* is a simple, one file, *XDCC* downloader written in python, so it should works out of the box on every system that
  has python3 installed.
* How it works
  This program uses a small IRC client library, [[https:github.com/jaraco/irc]], to connect to the specified server, join the
  chosen channel(if some channel are specified on command-line) and sends a *ctcp* message to the XDCC bot soliciting 
  the desired file. If the last part goes well then we start to receive the file via *DCC*.
* How to use
  #+CAPTION: General usage
  #+BEGIN_SRC bash
  xdcc -s <server-name> -p <port-number> -c <channel>  botname [action] [packs]
  #+END_SRC
  
If *server* and *port number* options are not specified, the default server and port are irc.rizon.net
and 6667, respectively. If no channel is specified then the program don't join any channel at all.
  
** Some examples
   
Print the bot's file list to stdout:
#+BEGIN_SRC bash
xdcc --stdout 'YOUR-BOT-NAME-HERE' list
#+END_SRC

Download the files given by the pack numbers 500,501,502,503 and 510:
#+BEGIN_SRC bash
xdcc 'YOUR-BOT-NAME-HERE' send '500-503,510'
#+END_SRC

Same as above, but supposing that the bot requires you to be logged in a specific channel:
#+BEGIN_SRC bash
xdcc -c '#ChannelNameHere' 'YOUR-BOT-NAME-HERE' send '500-503,510'
#+END_SRC

For more options just type =xdcc --help= in your shell:
#+BEGIN_SRC text
usage: xdcc [-h] [--server SERVER] [--channel CHANNEL] [--port PORT] [--stdout] [--nickname NICKNAME] [--verbose]
            bot {list,send} [packs]

positional arguments:
  bot                   The XDCC Bot name.
  {list,send}           Action to take. Use 'list' for get the file list from the bot. Use 'send' to get a file from the bot.
  packs                 Packs numbers of the desired files. Ex: '50-62,64,66,70-80'.

optional arguments:
  -h, --help            show this help message and exit
  --server SERVER, -s SERVER
                        The server to connect. The default is irc.rizon.net.
  --channel CHANNEL, -c CHANNEL
                        The channel to join. The default is to not join in any server.
  --port PORT, -p PORT  The port number of the server. The default is 6667.
  --stdout, -t          When used with the 'list' action, print the contents of the list file to the stdout.
  --nickname NICKNAME, -n NICKNAME
                        Nickname to be used in the server. If this option is not provided, a random permutation of 'anonymous' will
                        be used.
  --verbose, -v         Enable verbose mode.
#+END_SRC
* License  
[[file:LICENSE]]
